-- Visualização dos dados:
SELECT * FROM CATEGORIA;

SELECT * FROM CLIENTE;

SELECT * FROM ESTRELA;

SELECT * FROM EMPRESTIMO;

SELECT * FROM FILME;

SELECT * FROM FILME_ESTRELA;

SELECT * FROM BAIXA_EMPRESTIMO;

-- Criação de visualizações:
SELECT SUM(VALOR_ALUGUEL) AS VALOR_TOTAL_ALUGUEL FROM FILME;
SELECT MAX(VALOR_ALUGUEL) AS MAIOR_VALOR_ALUGUEL FROM FILME;
SELECT AVG(VALOR_ALUGUEL) AS VALOR_MEDIO_ALUGUEL FROM FILME;

SELECT SUM(VALOR_A_PAGAR) AS VALOR_TOTAL_EMPRESTIMOS FROM BAIXA_EMPRESTIMO;
SELECT MAX(VALOR_A_PAGAR) AS MAIOR_VALOR_EMPRESTIMOS FROM BAIXA_EMPRESTIMO;
SELECT AVG(VALOR_A_PAGAR) AS VALOR_MEDIO_EMPRESTIMOS FROM BAIXA_EMPRESTIMO;

-- Selecionar apenas valores de aluguéis acima da média de aluguéis:
SELECT * FROM BAIXA_EMPRESTIMO WHERE VALOR_A_PAGAR > (
SELECT AVG(VALOR_A_PAGAR) AS VALOR_MEDIO_EMPRESTIMOS FROM BAIXA_EMPRESTIMO);

-- Encontrar todos os filmes onde determinado ator participou:

-- Cláusula WHERE com condicionais:

SELECT F.TITULO, F.DURACAO_EM_MIN, C.DESCRICAO, E.NOME_REAL
FROM FILME F, CATEGORIA C, ESTRELA E, FILME_ESTRELA FE
WHERE F.ID = FE.FILME_ID
AND C.ID = F.CATEGORIA_ID
AND E.ID = FE.ESTRELA_ID
AND E.NOME_REAL = 'SCARLET JOHANSON';

-- Utilizando o JOIN:
SELECT F.TITULO, F.DURACAO_EM_MIN, C.DESCRICAO, E.NOME_REAL
FROM FILME_ESTRELA FE
JOIN FILME F ON F.ID = FE.FILME_ID
JOIN CATEGORIA C ON C.ID = F.CATEGORIA_ID
JOIN ESTRELA E ON E.ID = FE.ESTRELA_ID
WHERE E.NOME_REAL = 'SCARLET JOHANSON';