-- Visualização dos dados:
SELECT * FROM CATEGORIA;

SELECT * FROM CLIENTE;

SELECT * FROM ESTRELA;

SELECT * FROM EMPRESTIMO;

SELECT * FROM FILME;

SELECT * FROM FILME_ESTRELA;

SELECT * FROM BAIXA_EMPRESTIMO;

-- Criação de visualizações:
SELECT SUM(VALOR_ALUGUEL) AS VALOR_TOTAL_ALUGUEL FROM FILME;
SELECT MAX(VALOR_ALUGUEL) AS MAIOR_VALOR_ALUGUEL FROM FILME;
SELECT AVG(VALOR_ALUGUEL) AS VALOR_MEDIO_ALUGUEL FROM FILME;

SELECT SUM(VALOR_A_PAGAR) AS VALOR_TOTAL_EMPRESTIMOS FROM BAIXA_EMPRESTIMO;
SELECT MAX(VALOR_A_PAGAR) AS MAIOR_VALOR_EMPRESTIMOS FROM BAIXA_EMPRESTIMO;
SELECT AVG(VALOR_A_PAGAR) AS VALOR_MEDIO_EMPRESTIMOS FROM BAIXA_EMPRESTIMO;

-- Selecionar apenas valores de aluguéis acima da média de aluguéis:
SELECT * FROM BAIXA_EMPRESTIMO WHERE VALOR_A_PAGAR > (
SELECT AVG(VALOR_A_PAGAR) AS VALOR_MEDIO_EMPRESTIMOS FROM BAIXA_EMPRESTIMO);

-- View para analisar os dados dos filmes:

SELECT * FROM FILME_ESTRELA;

CREATE VIEW VW_DADOS_FILME (TITULO, DURACAO, CATEGORIA, VALOR, ATOR)
    AS SELECT F.TITULO, F.DURACAO_EM_MIN, C.DESCRICAO, F.VALOR_ALUGUEL, E.NOME_REAL
    FROM FILME F
    JOIN CATEGORIA C ON C.ID = F.CATEGORIA_ID
    LEFT JOIN FILME_ESTRELA FE ON FE.FILME_ID = F.ID
    LEFT JOIN ESTRELA E ON E.ID = FE.ESTRELA_ID;

SELECT * FROM VW_DADOS_FILME;