TRUNCATE TABLE CATEGORIA CASCADE;
TRUNCATE TABLE ESTRELA CASCADE;
TRUNCATE TABLE CLIENTE CASCADE;

INSERT INTO CATEGORIA(ID, DESCRICAO) VALUES (1, 'TERROR');
INSERT INTO CATEGORIA(ID, DESCRICAO) VALUES (2, 'COMÉDIA');
INSERT INTO CATEGORIA(ID, DESCRICAO) VALUES (3, 'AÇÃO');
INSERT INTO CATEGORIA(ID, DESCRICAO) VALUES (4, 'AVENTURA');
INSERT INTO CATEGORIA(ID, DESCRICAO) VALUES (5, 'DOCUMENTÁRIO');
INSERT INTO CATEGORIA(ID, DESCRICAO) VALUES (6, 'SUSPENSE');

INSERT INTO ESTRELA(ID, NOME, SOBRENOME, NOME_REAL) VALUES(1, 'SCARLET', 'JOHANSON', 'SCARLET JOHANSON');
INSERT INTO ESTRELA(ID, NOME, SOBRENOME, NOME_REAL) VALUES(2, 'JOHN', 'WEEK', 'XPTO');
INSERT INTO ESTRELA(ID, NOME, SOBRENOME, NOME_REAL) VALUES(3, 'HOMEM', 'DE FERRO', 'CARL MEGAN');
INSERT INTO ESTRELA(ID, NOME, SOBRENOME, NOME_REAL) VALUES(4, 'HOMEM', 'ARANHA', 'PETER PARK');
INSERT INTO ESTRELA(ID, NOME, SOBRENOME, NOME_REAL) VALUES(5, 'PELE', 'DA SILVA', 'JOÃO DE SOUZA');
INSERT INTO ESTRELA(ID, NOME, SOBRENOME, NOME_REAL) VALUES(6, 'RONALDINHO', 'GAÚCHO', 'RODRIGO LIMA');
INSERT INTO ESTRELA(ID, NOME, SOBRENOME, NOME_REAL) VALUES(7, 'AIRTON', 'SENNA', 'AIRTON SENNA');
INSERT INTO ESTRELA(ID, NOME, SOBRENOME, NOME_REAL) VALUES(8, 'BARACK', 'OBAMA', 'BARACK OBAMA');
INSERT INTO ESTRELA(ID, NOME, SOBRENOME, NOME_REAL) VALUES(9, 'LUCY', 'CRISLY', 'AMANDA CAMPOS');
INSERT INTO ESTRELA(ID, NOME, SOBRENOME, NOME_REAL) VALUES(10, 'LUKE', 'SKYWALTER', 'NAPOLEÃO BONAPARTE');

INSERT INTO CLIENTE(ID, NOME, SOBRENOME, TELEFONE, LOGRADOURO, CIDADE, ESTADO, CEP) VALUES (1, 'ANA', 'DE SOUZA', '4799985-4444', 'RUA 1', 'JOINVILLE', 'SANTA CATARINA', '88888-100');
INSERT INTO CLIENTE(ID, NOME, SOBRENOME, TELEFONE, LOGRADOURO, CIDADE, ESTADO, CEP) VALUES (2, 'AMANDA', 'CAMPOS', '4799985-4444', 'RUA 2', 'JOINVILLE', 'SANTA CATARINA', '88888-100');
INSERT INTO CLIENTE(ID, NOME, SOBRENOME, TELEFONE, LOGRADOURO, CIDADE, ESTADO, CEP) VALUES (3, 'ARIANE', 'DE LIMA', '4799985-4444', 'RUA 3', 'JOINVILLE', 'SANTA CATARINA', '88888-100');
INSERT INTO CLIENTE(ID, NOME, SOBRENOME, TELEFONE, LOGRADOURO, CIDADE, ESTADO, CEP) VALUES (4, 'BRUNO', 'DE CASTRO', '4799985-4444', 'RUA 4', 'JOINVILLE', 'SANTA CATARINA', '88888-100');
INSERT INTO CLIENTE(ID, NOME, SOBRENOME, TELEFONE, LOGRADOURO, CIDADE, ESTADO, CEP) VALUES (5, 'BERNARDO', 'HIERTZ', '4799985-4444', 'RUA 5', 'JOINVILLE', 'SANTA CATARINA', '88888-100');
INSERT INTO CLIENTE(ID, NOME, SOBRENOME, TELEFONE, LOGRADOURO, CIDADE, ESTADO, CEP) VALUES (6, 'BEATRIZ', 'MUELLER', '4799985-4444', 'RUA 6', 'JOINVILLE', 'SANTA CATARINA', '88888-100');
INSERT INTO CLIENTE(ID, NOME, SOBRENOME, TELEFONE, LOGRADOURO, CIDADE, ESTADO, CEP) VALUES (7, 'CARLOS', 'KORN', '4799985-4444', 'RUA 7', 'JOINVILLE', 'SANTA CATARINA', '88888-100');
INSERT INTO CLIENTE(ID, NOME, SOBRENOME, TELEFONE, LOGRADOURO, CIDADE, ESTADO, CEP) VALUES (8, 'CAROLINA', 'MATTOS', '4799985-4444', 'RUA 8', 'JOINVILLE', 'SANTA CATARINA', '88888-100');
INSERT INTO CLIENTE(ID, NOME, SOBRENOME, TELEFONE, LOGRADOURO, CIDADE, ESTADO, CEP) VALUES (9, 'CRISTIANO', 'GUEDES', '4799985-4444', 'RUA 9', 'JOINVILLE', 'SANTA CATARINA', '88888-100');
INSERT INTO CLIENTE(ID, NOME, SOBRENOME, TELEFONE, LOGRADOURO, CIDADE, ESTADO, CEP) VALUES (10, 'DIEGO', 'DE SOUZA', '4799985-4444', 'RUA 10', 'JOINVILLE', 'SANTA CATARINA', '88888-100');
INSERT INTO CLIENTE(ID, NOME, SOBRENOME, TELEFONE, LOGRADOURO, CIDADE, ESTADO, CEP) VALUES (11, 'DIOGENES', 'HERT', '4799985-4444', 'RUA 11', 'JOINVILLE', 'SANTA CATARINA', '88888-100');
INSERT INTO CLIENTE(ID, NOME, SOBRENOME, TELEFONE, LOGRADOURO, CIDADE, ESTADO, CEP) VALUES (12, 'JOÃO', 'DE SOUZA', '4799985-4444', 'RUA 12', 'JOINVILLE', 'SANTA CATARINA', '88888-100');
INSERT INTO CLIENTE(ID, NOME, SOBRENOME, TELEFONE, LOGRADOURO, CIDADE, ESTADO, CEP) VALUES (13, 'JULIANA', 'DE SOUZA', '4799985-4444', 'RUA 13', 'JOINVILLE', 'SANTA CATARINA', '88888-100');
INSERT INTO CLIENTE(ID, NOME, SOBRENOME, TELEFONE, LOGRADOURO, CIDADE, ESTADO, CEP) VALUES (14, 'LUCAS', 'LIMA', '4799985-4444', 'RUA 14', 'JOINVILLE', 'SANTA CATARINA', '88888-100');
